### PR TITLE
Fix fc-lc.com bypass (closes #1558)

### LINKED ISSUE #1558: fc-lc.com
Example: https://fc-lc.com/test

### PR DESCRIPTION
**Pull request by FireMasterK**
Lmk if any changes are needed, this closes #1558.

### CODE REVIEW

**Comment by Sainan** [comment]
Why did you remove the regex?

**Comment by FireMasterK** [comment]
That was because the the other domains are just used as blog domains so I thought it would be okay to leave those out considering that we don't even need to visit them, what do you think?

If you think we shouldn't do that, I'll add it back as well as fix the bypass the blog pages as those appear to not work anymore

**Comment by FireMasterK** [comment]
Why have you takes this approach? You just called crowdBypass() without ever contributing to it which makes it redundant... Also, your approach requires you to solve a ReCaptcha.

**Comment by Sainan** [comment]
Your code didn't seem to work, so I made my own. The AdLinkFly bypass & crowd bypass backend can do most of the work.

**Comment by FireMasterK** [comment]
I did test it by adding it Custom Bypass and it did work then, not sure what could have happened, can you see what's the response you get from https://fc.lc/links/go? I may have set the delay too low (8000ms), could you try changing it 10000?

I just tested your changes and crowd bypass doesn't seem to work (doesn't seem to save the URL after solving)

**Comment by Sainan** [comment]
I don't remember what exactly it returned but it was an error with no URL.

Anyway, you are correct that it doesn't contribute, I completely forgot to test that. 🙄

**Comment by FireMasterK** [comment]
An error with no URL means that the delay was too less, try changing the 8000 to 10000 and see what happens, it could have been that my page takes a long time to load on my end, thus compensating for the missing delay.

**Comment by Sainan** [comment]
You're free to test it, but as far as I understand it, if you send a wrong request to the "go" endpoint, the token is invalidated. And in general, bypassing a captcha isn't the best idea, even if it's part of a scummy website, and I don't even understand how Google allows it — I assume they just can't be arsed to deal with it.

**Comment by FireMasterK** [comment]
I just tested this on my end, could you confirm it works on yours?
```
	domainBypass("fc-lc.com",()=>ifElement("form",f=>{
		crowdBypass()
		document.querySelector(".btn").disabled = true
		const data = new URLSearchParams(new FormData(f))
		new Promise(resolve => setTimeout(resolve, 10000)).then(()=>fetch('https://fc.lc/links/go', {
			method: 'post',
			body: data,
		}).then(r=>r.json()).then(json=>contributeAndNavigate(json.url)))
	}))
```

**Comment by Sainan** [comment]
It did work just now, but in my opinion, it's a bad user experience. Here's an idea: Redirect to `"https://fcc.lc/2020/06/how-to-develop-your-artificial-intelligence-ai-strategy/?a=" + btoa(pathname.substr(1)` to skip the catpcha if you must insist

**Pull request closed without merging**
