### PR TITLE
Fix #1549

### LINKED ISSUE #1549: https://links.shortenbuddy.com/
https://links.shortenbuddy.com/

https://links.shortenbuddy.com/k6Vn

### PR DESCRIPTION
**Pull request by FireMasterK**
This will directly take us to the adlinkfly page.

### CODE REVIEW

**Comment by Sainan** [comment]
Just as a note:
image

**Comment by Sainan** [comment]
Merged into master as 6de95ca7b57ffbe82e62b443dcb8b39bdd84c4eb.

**Comment by FireMasterK** [comment]
You see such a git history because of my master branch is out of date with this repo, that's unrelated because that's my branch for this PR (pr-7) is up to date with this repo :)

**Comment by Sainan** [comment]
I understand that, I'm just making you aware that your "Auto Update" missed a commit.

**Pull request closed without merging**
