### PR TITLE
Add bypass for www2.tirexo.ai link protection (www6.journaldupirate.net)

### PR DESCRIPTION
**Pull request by JohnTitor2036**

### CODE REVIEW

**Comment by Sainan** [comment]
Example link?

**Comment by JohnTitor2036** [comment]
This link : 
https://www6.journaldupirate.net/go_to/R3RuOWNNNmpXb3QyMXdqckMzcElqOWhRNTJLK3A5TC9NUlprSkljazBkSEg2QWgwQXFoT2RwY0NLSmtvcGwvRkVRNzB6QkZvUHRPV0Z2ZzBvN1lmc3c9PQ

Will lead to this site https://uptobox.com/7augxkk9u546?aff_id=12655137

**Comment by Sainan** [comment]
It says "This link has been deleted or expired." Where did you get it from?

**Comment by JohnTitor2036** [comment]
My bad, the links are probably generate on the fly with a expable token.
https://www2.tirexo.ai/films-gratuit/755878-godzilla-vs-kong-WEB-DL%201080p-VOSTFR.html#show_links:~:text=UPTOBOX.COM
You can click any "Télécharger" Hyperlink

**Pull request closed without merging**
