### PR TITLE
Add cheatsquad download bypass

### PR DESCRIPTION
**Pull request by SiebeDW**
This bypass makes it so all the steps are checked

### CODE REVIEW

**Comment by Sainan** [comment]
Could you provide an example link?

**Comment by SiebeDW** [comment]
https://cheatsquad.gg/dl/7zmuAY/

**Comment by SiebeDW** [comment]
Pretty sure it wont work in your commit. Problem is that domain check is chaosity.cheatsquad.gg
and the download is not chaosity.cheatsquad.gg.

**Comment by Sainan** [comment]
It does seem to work tho?

**Comment by SiebeDW** [comment]
https://gyazo.com/af44752c73896342c1b650c486065605
Doesnt work for me :/

**Comment by Sainan** [comment]
Can you not just press the download button?

**Comment by SiebeDW** [comment]
I need to complete the steps first

**Pull request closed without merging**
