### PR TITLE
Add boost.ink step finisher

### PR DESCRIPTION
**Pull request by respecting**
Doesn't redirect to site, just finishes steps since I don't know how to make it redirect
Example link: https://bst.gg/ne23

### CODE REVIEW

**Comment by FireMasterK** [comment]
Sainan owns boost.ink fyi

**Comment by respecting** [comment]
high chance it wont be accepted :/

**Comment by FireMasterK** [comment]
You can at least use it as a custom bypass in case it doesn't :D

**Comment by respecting** [comment]
Yeah

**Comment by respecting** [comment]
Why was Universal Bypass removed from hell.sh as one of their projects?

**Comment by FireMasterK** [comment]
Not sure why that is, if I had to guess hell-sh probably had multiple members and Universal-Bypass is Sainan's personal project.

**Comment by respecting** [comment]
It was owned by timmyRS before, and after the switch, I think it was removed.

**Comment by Sainan** [comment]
Universal Bypass is a personal project, but I still have this conflict of interest. We'll get there post-capitalism.

**Pull request closed without merging**
