### PR TITLE
Add 5mod-file.ru bypass (#1724)

### PR DESCRIPTION
**Pull request by RobbyAJM**

### CODE REVIEW

**Comment by Sainan** [comment]
Example link?

**Comment by RobbyAJM** [comment]
https://5mod-file.ru/download/file/107402.php

**Comment by Sainan** [comment]
I see now that your PRs are related to issues. Use "closes #...." so this is more apparent. And maybe try to follow my code style & comments, so I don't have to cherry pick and amend. ;)

**Comment by RobbyAJM** [comment]
Sure, thanks.

**Pull request closed without merging**
