### PR TITLE
Add gplinks.co & droidfilehost.com bypass (closes #1812)

### LINKED ISSUE #1812: gplinks.co
Eg link: https://gplinks.co/RyGymjJ9

This site is heavily ad-infested using adblocker is advised. You need to click 'Open-Continue'(Bottom) and "X"(Upper right) multiple times.
Destination: https://drive.google.com/file/d/1aBfmwbnaHZvwdHjs-UBWWTc-Ner1mXX6/view

### PR DESCRIPTION
**Pull request by RobbyAJM**
Eg link: https://gplinks.co/RyGymjJ9

### CODE REVIEW

**Comment by RobbyAJM** [comment]
Pardon me for multiple commits ._.

**Comment by Sainan** [comment]
Wouldn't a crowd bypass be apropriate for an unskippable wait?

**Comment by RobbyAJM** [comment]
Yeah I forgot about that, but anyways crowd bypass might be good if combined with my code above.

**Comment by RobbyAJM** [comment]
I've added crowd bypass for gplinks.co

**Comment by as1087e** [comment]
please add droplinks.co

**Pull request merged**
