### PR TITLE
Fix #1534

### LINKED ISSUE #1534: androiddownload.net
https://www.androiddownload.net/e35ec1269e2f8a437f8c8419dc50e7d6/[ARTEAM]_Neo_Monsters_v2.14.1-signed.apk

### PR DESCRIPTION
**Pull request by FireMasterK**
There seems to be a server-side timer so, replacing setInterval won't work.

### CODE REVIEW

**Comment by Sainan** [comment]
If it has backend validation, why not just dump it in with the rest on [line 731](https://github.com/Sainan/Universal-Bypass/blob/master/injection_script.js#L731)?

**Comment by FireMasterK** [comment]
Hmmm, don't we want to automatically go to the download link? We can't skip the timer but we can go to the final destination automatically without any captchas.

**Comment by Sainan** [comment]
Are there any captchas? If so, then I suppose there is some value to this. Maybe inserting the "infoFile" notice in addition to the bypass so the user doesn't get mad?

**Comment by FireMasterK** [comment]
There are none, I think that's a good idea, I'll add the infoFileHoster notice in this pr

**Comment by Sainan** [comment]
Made some changes with cd05633199f737cf5ad0aaf96083b85625400468.

**Pull request closed without merging**
