### PR TITLE
Redirect "tudofinanceiro.club" to "mundofinanceiro.club"

### PR DESCRIPTION
**Pull request by caiocinel**

### CODE REVIEW

**Comment by caiocinel** [comment]
????

**Comment by FireMasterK** [comment]
Maybe explain the purpose of your change?

**Comment by caiocinel** [comment]
> Maybe explain the purpose of your change?

The blocker's address was changed to "mundofinanceiro.club", ceasing to be "tudofinanceiro.club", so much so that I added support for the specified address myself. It's just to keep everything running smoothly.

**Comment by Sainan** [comment]
1. Dont remove the old domain
2. Provide an example link

**Pull request closed without merging**
