### PR TITLE
Add psarips adlinkfly bypass

### LINKED ISSUE #1430: psarips.(com|net|org|eu|in|one|xyz)/exit/
Hi. Psarips https://psarips.(com|net|org|eu|in|one|xyz)/exit/??? links always(or usually) open different shorteners. Its opening new captcha for every different shortener and universal bypass can't bypass if noone manually skips all different shorteners. Target link always same but shorteners different. Can you add skip support for https://psarips.xyz/exit/??? links (as crowd bypass source)?

**source:**
```
https://psarips.com/exit/4aae9c837bfc5617de4440549717029f/r1s0PF9U2DG+jb8lMV5k+FDA6zaPtuceVA9wSpjSncYZWVCcotlGa9+8YtfatStM:bks5MjR0R3VHNVFLM3ZWSy9ocllCZz09:nK924tGuG5QK3vVK/hrYBmNhbnR0b3VjaHRoaXM=
https://psarips.net/exit/4aae9c837bfc5617de4440549717029f/r1s0PF9U2DG+jb8lMV5k+FDA6zaPtuceVA9wSpjSncYZWVCcotlGa9+8YtfatStM:bks5MjR0R3VHNVFLM3ZWSy9ocllCZz09:nK924tGuG5QK3vVK/hrYBmNhbnR0b3VjaHRoaXM=
https://psarips.org/exit/4aae9c837bfc5617de4440549717029f/r1s0PF9U2DG+jb8lMV5k+FDA6zaPtuceVA9wSpjSncYZWVCcotlGa9+8YtfatStM:bks5MjR0R3VHNVFLM3ZWSy9ocllCZz09:nK924tGuG5QK3vVK/hrYBmNhbnR0b3VjaHRoaXM=
https://psarips.eu/exit/4aae9c837bfc5617de4440549717029f/r1s0PF9U2DG+jb8lMV5k+FDA6zaPtuceVA9wSpjSncYZWVCcotlGa9+8YtfatStM:bks5MjR0R3VHNVFLM3ZWSy9ocllCZz09:nK924tGuG5QK3vVK/hrYBmNhbnR0b3VjaHRoaXM=
https://psarips.in/exit/4aae9c837bfc5617de4440549717029f/r1s0PF9U2DG+jb8lMV5k+FDA6zaPtuceVA9wSpjSncYZWVCcotlGa9+8YtfatStM:bks5MjR0R3VHNVFLM3ZWSy9ocllCZz09:nK924tGuG5QK3vVK/hrYBmNhbnR0b3VjaHRoaXM=
https://psarips.one/exit/4aae9c837bfc5617de4440549717029f/r1s0PF9U2DG+jb8lMV5k+FDA6zaPtuceVA9wSpjSncYZWVCcotlGa9+8YtfatStM:bks5MjR0R3VHNVFLM3ZWSy9ocllCZz09:nK924tGuG5QK3vVK/hrYBmNhbnR0b3VjaHRoaXM=
https://psarips.xyz/exit/4aae9c837bfc5617de4440549717029f/r1s0PF9U2DG+jb8lMV5k+FDA6zaPtuceVA9wSpjSncYZWVCcotlGa9+8YtfatStM:bks5MjR0R3VHNVFLM3ZWSy9ocllCZz09:nK924tGuG5QK3vVK/hrYBmNhbnR0b3VjaHRoaXM=
```

**redirect(not the full list):**
```
https://fcdot.lc/2020/07/things-your-competitors-can-teach-you-about-digital-marketing/?a=R3hyTFVuUXY=
https://linksly.co/qHgC
https://ouo.press/VOK4zD
https://dz4win.com/7xwAe
https://news.techrfour.com/rDYCxfqM
https://aii.sh/wKjd
https://tmearn.com/KT9D
https://icutlink.com/6UsdkhJ93
https://short.pe/7aieM
https://adsrt.live/3NW3H
https://adbull.org/NUv40
https://oke.io/Hg6a
https://shotly.io/CY6v
https://shurt.pw/7aieM
https://pingit.link/4iT7
```

**target:** `https://www.keeplinks.org/p/5551010268a89`

### PR DESCRIPTION
**Pull request by sayapemula**
Fix #1430?

### CODE REVIEW

**Comment by Sainan** [comment]
That's just a major change to how crowd bypass behaves with a bypass clipboard value.

**Comment by sayapemula** [comment]
I thought I had followed your idea of using the bypass clipboard to tell the AdLinkFly bypass that the user came from psarips site.
https://github.com/Sainan/Universal-Bypass/pull/1515#issuecomment-690299946

**Comment by Sainan** [comment]
Yeah, you took the idea, you implemented it, but you forgot scalability. I implemented it myself with ed87674ef22ba4d045be906d07211b7701e4025f.

**Comment by sayapemula** [comment]
I think you forgot something about AdLinkFly, which has 2 steps, the first step is post recaptcha, if the form action in the first step is not added `"#bypassClipboard="+bypassClipboard` then in the second step there is no `bypassClipboard`.

**Comment by Sainan** [comment]
Yeah, I confused bypass clipboard with the ignore crowd bypass.

**Pull request closed without merging**
